# config.toml
#
# Use this file to configure how thehttpbot runs.
# Any credentials should go in the `.env` file.

[bot]
sync_on_start = true

[logging]
# https://docs.python.org/3/library/logging.html#levels
level = 20
